apiVersion: v2
publisher: redhat-developer
name: che-workspace-telemetry-woopra-backend
version: 0.0.2
type: Che Plugin
displayName: Woopra Telemetry Backend
description: Telemetry plugin to send information to Woopra
title: Che Workspace Telemetry Woopra Backend
category: Other
spec:
  workspaceEnv:
    - name: CHE_WORKSPACE_TELEMETRY_BACKEND_PORT
      value: '4167'
  containers:
  - name: che-workspace-telemetry-woopra-backend
    image: quay.io/openshiftio/che-workspace-telemetry-woopra-backend:latest
    env:
      - name: CHE_API
        value: $(CHE_API_INTERNAL)
      - name: CHE_FABRIC8_ANALYTICS_WOOPRA_DOMAIN
        value: ''
      - name: CHE_FABRIC8_ANALYTICS_SEGMENT_WRITE_KEY
        value: ''
      - name: WOOPRA_DOMAIN_ENDPOINT
        value: $CHE_API/fabric8-che-analytics/woopra-domain
      - name: SEGMENT_WRITE_KEY_ENDPOINT
        value: $CHE_API/fabric8-che-analytics/segment-write-key

